--- #YAML:1.0
name: Geo-Coordinates-RDNAP
version: 0.02
author:
  - Eugene van der Pijll
abstract: |-
  Convert coordinates from/to the Dutch RD-NAP system
license: perl
requires:
  Params::Validate: 0
recommends:
  Test::Pod: 1
build_requires:
  Test::More: 0.34
provides:
  Geo::Coordinates::RDNAP:
    file: lib/Geo/Coordinates/RDNAP.pm
    version: 0.02
generated_by: Module::Build version 0.2611
